[workspace]
channels = ["robostack-jazzy", "conda-forge"]
name = "okvis_onboard"
platforms = ["linux-64"]
version = "0.1.0"

[environments]
ros2 = ["jazzy"]
zed = ["zed", "jazzy"]
orbbec = ["orbbec", "jazzy"]
okvis2x = ["okvis2x", "jazzy"]

[feature.jazzy.dependencies]
python = "3.12.*"
ros-jazzy-desktop = "*"
colcon-common-extensions = "*"
ros-jazzy-tf2-tools = "*"

[feature.jazzy.pypi-dependencies]
evo = "*"
rosbags="*"

[feature.jazzy.activation.env]
ROS_DOMAIN_ID="0"
# FASTDDS_BUILTIN_TRANSPORTS="LARGE_DATA"
RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp"
# ROS_MASTER_URI="http://localhost:11311"
# ROS_HOSTNAME="localhost"
# ROS_IP="127.0.0.1"

[feature.zed.dependencies]
cmake = ">=3.22.1,<4"
ninja = "*"
make = "*"
gcc_linux-64 = "13.*"
gxx_linux-64 = "13.*"
git = "*"
pkg-config = "*"
nlohmann_json = "*"
ros-jazzy-ament-cmake = "*"
ros-jazzy-ament-cmake-auto = "*"
ros-jazzy-ament-cmake-copyright = "*"
ros-jazzy-ament-cmake-cppcheck = "*"
ros-jazzy-ament-cmake-lint-cmake = "*"
ros-jazzy-ament-cmake-pep257 = "*"
ros-jazzy-ament-cmake-uncrustify = "*"
ros-jazzy-ament-cmake-xmllint = "*"
ros-jazzy-ament-lint-auto = "*"
ros-jazzy-backward-ros = "*"
ros-jazzy-builtin-interfaces = "*"
ros-jazzy-compressed-depth-image-transport = "*"
ros-jazzy-compressed-image-transport = "*"
ros-jazzy-diagnostic-msgs = "*"
ros-jazzy-diagnostic-updater = "*"
ros-jazzy-geographic-msgs = "*"
ros-jazzy-geometry-msgs = "*"
ros-jazzy-image-transport = "*"
ros-jazzy-image-transport-plugins = "*"
ros-jazzy-launch-ros = "*"
ros-jazzy-nav-msgs = "*"
ros-jazzy-nmea-msgs = "*"
ros-jazzy-rclcpp = "*"
ros-jazzy-rclcpp-components = "*"
ros-jazzy-rcutils = "*"
ros-jazzy-robot-localization = "*"
ros-jazzy-rosgraph-msgs = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-std-msgs = "*"
ros-jazzy-std-srvs = "*"
ros-jazzy-stereo-msgs = "*"
ros-jazzy-tf2 = "*"
ros-jazzy-tf2-geometry-msgs = "*"
ros-jazzy-tf2-ros = "*"
ros-jazzy-theora-image-transport = "*"
ros-jazzy-visualization-msgs = "*"
ros-jazzy-xacro = "*"
ros-jazzy-rosidl-default-generators = "*"
ros-jazzy-rosidl-default-runtime = "*"
ros-jazzy-shape-msgs = "*"
ros-jazzy-zed-description = "*"

[feature.zed.tasks]
clone-zed = { cmd = "mkdir -p zed_ws/src && bash -c '[ -d zed_ws/src/zed-ros2-wrapper ] || git clone https://github.com/stereolabs/zed-ros2-wrapper.git zed_ws/src/zed-ros2-wrapper' && bash -c '[ -d zed_ws/src/zed-ros2-interfaces ] || git clone https://github.com/stereolabs/zed-ros2-interfaces.git zed_ws/src/zed-ros2-interfaces'" }
build-zed = { cmd = "cd zed_ws && colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release --parallel-workers $(nproc)", depends-on = ["clone-zed"] }
setup = { depends-on = ["build-zed"] }

[feature.zed.activation]
scripts = ["zed_ws/install/setup.bash"]

[feature.orbbec.dependencies]
cmake = ">=3.22.1,<4"
ninja = "*"
make = "*"
gcc_linux-64 = "13.*"
gxx_linux-64 = "13.*"
git = "*"
pkg-config = "*"
gflags = "*"
nlohmann_json = "*"
glog = "*"
elfutils = "*"
openssl = "*"
libgl-devel = "*"
ros-jazzy-backward-ros = "*"
colcon-common-extensions = "*"
ros-jazzy-ament-cmake = "*"
ros-jazzy-rclcpp = "*"
ros-jazzy-rclcpp-components = "*"
ros-jazzy-cv-bridge = "*"
ros-jazzy-image-transport = "*"
ros-jazzy-image-transport-plugins = "*"
ros-jazzy-compressed-image-transport = "*"
ros-jazzy-image-publisher = "*"
ros-jazzy-camera-info-manager = "*"
ros-jazzy-diagnostic-updater = "*"
ros-jazzy-diagnostic-msgs = "*"
ros-jazzy-statistics-msgs = "*"
ros-jazzy-xacro = "*"
ros-jazzy-rosidl-default-generators = "*"
ros-jazzy-rosidl-default-runtime = "*"
ros-jazzy-ament-index-cpp = "*"
ros-jazzy-builtin-interfaces = "*"
ros-jazzy-std-srvs = "*"
ros-jazzy-tf2 = "*"
ros-jazzy-tf2-ros = "*"
ros-jazzy-tf2-sensor-msgs = "*"
ros-jazzy-tf2-msgs = "*"
ros-jazzy-std-msgs = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-ament-lint-auto = "*"
ros-jazzy-ament-lint-common = "*"

[feature.orbbec.tasks]
clone-orbbec = { cmd = "mkdir -p orbbec_ws/src && bash -c '[ -d orbbec_ws/src/OrbbecSDK_ROS2 ] || git clone -b v2-main https://github.com/orbbec/OrbbecSDK_ROS2.git orbbec_ws/src/OrbbecSDK_ROS2'" }
build-orbbec = { cmd = "cd orbbec_ws && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release", depends-on = ["clone-orbbec"] }
setup = { depends-on = ["build-orbbec"] }

[feature.orbbec.activation]
scripts = ["orbbec_ws/install/setup.bash"]

[feature.okvis2x.dependencies]
cmake = ">=3.14"
make = "*"
gcc_linux-64 = "13.*"
gxx_linux-64 = "13.*"
glog = "<0.7.0"
gflags = "*"
eigen = "3.4.*"
suitesparse = "*"
geographiclib-cpp = "*"
pkg-config = "*"
git = "*"
python = "3.12.*"
pip = "*"
setuptools = "<80.0.0"

[feature.okvis2x.pypi-dependencies]
torch = "==2.9.1"

[feature.okvis2x.activation.env]
CMAKE_PREFIX_PATH = "$CONDA_PREFIX:$CONDA_PREFIX/lib/python3.12/site-packages/torch:$CONDA_PREFIX/targets/x86_64-linux"
LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$CONDA_PREFIX/targets/x86_64-linux/lib:$LD_LIBRARY_PATH"

[feature.okvis2x.activation]
scripts = ["okvis_ws/install/setup.bash"]

[feature.okvis2x.tasks]
clone = "mkdir -p okvis_ws/src && cd okvis_ws/src && (git clone --recurse-submodules https://github.com/goldenpuffle123/okvis2x_femtobolt.git || true) && (git clone https://github.com/ethz-mrl/language_feature_msgs.git || true) && (git clone https://github.com/ethz-mrl/language_feature_node.git || true)"

# Mapping without color
# build = "cd okvis_ws && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_ROS2=ON -DUSE_NN=OFF -DHAVE_LIBREALSENSE=OFF -DUSE_COLIDMAP=OFF -DCERES_USE_CUDA=OFF -DCMAKE_DISABLE_FIND_PACKAGE_CUDA=ON -DCMAKE_DISABLE_FIND_PACKAGE_CUDAToolkit=ON"

# Mapping with color
build = "cd okvis_ws && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_ROS2=ON -DUSE_NN=OFF -DHAVE_LIBREALSENSE=OFF -DUSE_COLIDMAP=ON -DCERES_USE_CUDA=OFF -DCMAKE_DISABLE_FIND_PACKAGE_CUDA=ON -DCMAKE_DISABLE_FIND_PACKAGE_CUDAToolkit=ON"

setup = { depends-on = ["clone", "build"] }